"""
Fetches comment previews from GitHub Discussions (used by Giscus) and writes
_data/comments_preview.yml so Jekyll can render them on the blog listing page.

Uses the built-in GITHUB_TOKEN — no extra secrets needed.
"""
import json
import os
import urllib.request

CATEGORY_ID = "DIC_kwDOC9UEAM4C5sKq"

QUERY = """
{
  repository(owner: "dylanbeattie", name: "dylanbeattie.net") {
    discussions(first: 100, categoryId: "%s", orderBy: {field: UPDATED_AT, direction: DESC}) {
      nodes {
        title
        comments(first: 3) {
          totalCount
          nodes {
            author { login }
            bodyText
            createdAt
          }
        }
      }
    }
  }
}
""" % CATEGORY_ID

token = os.environ["GITHUB_TOKEN"]
req = urllib.request.Request(
    "https://api.github.com/graphql",
    data=json.dumps({"query": QUERY}).encode(),
    headers={
        "Authorization": f"bearer {token}",
        "Content-Type": "application/json",
    }
)
with urllib.request.urlopen(req) as resp:
    data = json.loads(resp.read())

if "errors" in data:
    raise RuntimeError(f"GraphQL errors: {data['errors']}")

discussions = data["data"]["repository"]["discussions"]["nodes"]

lines = ["# Auto-generated by fetch-comments workflow. Do not edit manually."]
count_written = 0
for d in discussions:
    count = d["comments"]["totalCount"]
    if count == 0:
        continue
    count_written += 1
    # Discussion title is set by Giscus to the page pathname
    pathname = d["title"]
    lines.append(f"- pathname: {json.dumps(pathname)}")
    lines.append(f"  count: {count}")
    lines.append(f"  comments:")
    for c in d["comments"]["nodes"]:
        author = c["author"]["login"] if c["author"] else "anonymous"
        raw = c["bodyText"].replace("\n", " ").replace("\r", "").strip()
        excerpt = (raw[:157] + "\u2026") if len(raw) > 157 else raw
        created_at = c.get("createdAt", "")
        lines.append(f"    - author: {json.dumps(author)}")
        lines.append(f"      excerpt: {json.dumps(excerpt)}")
        lines.append(f"      created_at: {json.dumps(created_at)}")

with open("_data/comments_preview.yml", "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"Wrote {count_written} discussions with comments out of {len(discussions)} total.")
